[project]
name = "pangolin-operator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kopf>=1.38.0",
    "kubernetes>=33.1.0",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
    "structlog>=25.4.0",
]
